# Generated by Django 4.1.7 on 2023-04-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('notification', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='RoomImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=200)),
                ('sequence', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.room')),
            ],
            options={
                'db_table': 'room_images',
            },
        ),
    ]
